# Generated by Django 3.0.6 on 2020-07-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200605_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='update',
        ),
    ]
